// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/get_daily_prices": {
            "get": {
                "description": "Fetch daily price data for a security by ticker or ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get daily prices for a security",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Security ticker symbol",
                        "name": "ticker",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Security ID",
                        "name": "security_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetDailyPricesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/get_etf_holdings": {
            "get": {
                "description": "Fetch holdings for an ETF or mutual fund by ticker or ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get ETF holdings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ETF ticker symbol",
                        "name": "ticker",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Security ID",
                        "name": "security_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetETFHoldingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/sync-securities": {
            "post": {
                "description": "Synchronize the securities database with AlphaVantage listing status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Sync securities from AlphaVantage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios": {
            "post": {
                "description": "Create a new portfolio with optional memberships. Accepts JSON or multipart/form-data with a CSV file.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolios"
                ],
                "summary": "Create a new portfolio",
                "parameters": [
                    {
                        "description": "Portfolio to create (JSON)",
                        "name": "portfolio",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.CreatePortfolioRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Portfolio metadata as JSON (multipart)",
                        "name": "metadata",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "CSV file with ticker,percentage_or_shares columns (multipart)",
                        "name": "memberships",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.PortfolioWithMemberships"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/compare": {
            "post": {
                "description": "Compare two portfolios over a time period, showing membership differences and performance metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolios"
                ],
                "summary": "Compare two portfolios",
                "parameters": [
                    {
                        "description": "Comparison parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CompareResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{id}": {
            "get": {
                "description": "Retrieve a portfolio and its memberships by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolios"
                ],
                "summary": "Get a portfolio by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Portfolio ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PortfolioWithMemberships"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "UserID": []
                    }
                ],
                "description": "Update a portfolio's name and/or memberships. Accepts JSON or multipart/form-data with a CSV file.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolios"
                ],
                "summary": "Update a portfolio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Portfolio ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Portfolio updates (JSON)",
                        "name": "portfolio",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.UpdatePortfolioRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Portfolio metadata as JSON (multipart)",
                        "name": "metadata",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "CSV file with ticker,percentage_or_shares columns (multipart)",
                        "name": "memberships",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PortfolioWithMemberships"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserID": []
                    }
                ],
                "description": "Delete a portfolio by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolios"
                ],
                "summary": "Delete a portfolio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Portfolio ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/portfolios": {
            "get": {
                "description": "Get all portfolios belonging to a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List user's portfolios",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PortfolioListItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CompareRequest": {
            "type": "object",
            "required": [
                "end_period",
                "portfolio_a",
                "portfolio_b",
                "start_period"
            ],
            "properties": {
                "end_period": {
                    "$ref": "#/definitions/models.FlexibleDate"
                },
                "portfolio_a": {
                    "type": "integer"
                },
                "portfolio_b": {
                    "type": "integer"
                },
                "start_period": {
                    "$ref": "#/definitions/models.FlexibleDate"
                }
            }
        },
        "models.CompareResponse": {
            "type": "object",
            "properties": {
                "absolute_similarity_score": {
                    "type": "number"
                },
                "performance_metrics": {
                    "$ref": "#/definitions/models.PerformanceMetrics"
                },
                "portfolio_a": {
                    "$ref": "#/definitions/models.PortfolioSummary"
                },
                "portfolio_b": {
                    "$ref": "#/definitions/models.PortfolioSummary"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Warning"
                    }
                }
            }
        },
        "models.CreatePortfolioRequest": {
            "type": "object",
            "required": [
                "name",
                "owner_id",
                "portfolio_type"
            ],
            "properties": {
                "memberships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MembershipRequest"
                    }
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "portfolio_type": {
                    "$ref": "#/definitions/models.PortfolioType"
                }
            }
        },
        "models.DailyValue": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "models.ETFHoldingDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "security_id": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ExpandedMembership": {
            "type": "object",
            "properties": {
                "allocation": {
                    "description": "Decimal allocation (0.60 = 60%)",
                    "type": "number"
                },
                "security_id": {
                    "type": "integer"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MembershipSource"
                    }
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.FlexibleDate": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "models.GetDailyPricesResponse": {
            "type": "object",
            "properties": {
                "data_points": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "prices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PriceData"
                    }
                },
                "security_id": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.GetETFHoldingsResponse": {
            "type": "object",
            "properties": {
                "holdings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ETFHoldingDTO"
                    }
                },
                "name": {
                    "type": "string"
                },
                "pull_date": {
                    "type": "string"
                },
                "security_id": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Warning"
                    }
                }
            }
        },
        "models.MembershipRequest": {
            "type": "object",
            "required": [
                "percentage_or_shares"
            ],
            "properties": {
                "percentage_or_shares": {
                    "type": "number"
                },
                "security_id": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "models.MembershipSource": {
            "type": "object",
            "properties": {
                "allocation": {
                    "description": "Proportion of this security's allocation from this source (sums to 1.0)",
                    "type": "number"
                },
                "security_id": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.PerformanceMetrics": {
            "type": "object",
            "properties": {
                "portfolio_a_metrics": {
                    "$ref": "#/definitions/models.PortfolioPerformance"
                },
                "portfolio_b_metrics": {
                    "$ref": "#/definitions/models.PortfolioPerformance"
                }
            }
        },
        "models.Portfolio": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "portfolio_type": {
                    "$ref": "#/definitions/models.PortfolioType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PortfolioListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "portfolio_type": {
                    "$ref": "#/definitions/models.PortfolioType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PortfolioMembership": {
            "type": "object",
            "properties": {
                "percentage_or_shares": {
                    "type": "number"
                },
                "portfolio_id": {
                    "type": "integer"
                },
                "security_id": {
                    "type": "integer"
                }
            }
        },
        "models.PortfolioPerformance": {
            "type": "object",
            "properties": {
                "daily_values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DailyValue"
                    }
                },
                "dividends": {
                    "type": "number"
                },
                "end_value": {
                    "type": "number"
                },
                "gain_dollar": {
                    "type": "number"
                },
                "gain_percent": {
                    "type": "number"
                },
                "sharpe_ratios": {
                    "$ref": "#/definitions/models.SharpeRatios"
                },
                "start_value": {
                    "type": "number"
                }
            }
        },
        "models.PortfolioSummary": {
            "type": "object",
            "properties": {
                "direct_membership": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExpandedMembership"
                    }
                },
                "expanded_memberships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExpandedMembership"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.PortfolioType"
                }
            }
        },
        "models.PortfolioType": {
            "type": "string",
            "enum": [
                "Ideal",
                "Active",
                "Historic"
            ],
            "x-enum-varnames": [
                "PortfolioTypeIdeal",
                "PortfolioTypeActive",
                "PortfolioTypeHistoric"
            ]
        },
        "models.PortfolioWithMemberships": {
            "type": "object",
            "properties": {
                "memberships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PortfolioMembership"
                    }
                },
                "portfolio": {
                    "$ref": "#/definitions/models.Portfolio"
                }
            }
        },
        "models.PriceData": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "security_id": {
                    "type": "integer"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "models.SharpeRatios": {
            "type": "object",
            "properties": {
                "daily": {
                    "type": "number"
                },
                "monthly": {
                    "type": "number"
                },
                "three_month": {
                    "type": "number"
                },
                "yearly": {
                    "type": "number"
                }
            }
        },
        "models.UpdatePortfolioRequest": {
            "type": "object",
            "properties": {
                "memberships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MembershipRequest"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Warning": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/models.WarningCode"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.WarningCode": {
            "type": "string",
            "enum": [
                "W1001",
                "W1002"
            ],
            "x-enum-comments": {
                "WarnPartialETFExpansion": "ETF only partially expanded, normalized",
                "WarnUnresolvedETFHolding": "individual unresolved holding"
            },
            "x-enum-descriptions": [
                "individual unresolved holding",
                "ETF only partially expanded, normalized"
            ],
            "x-enum-varnames": [
                "WarnUnresolvedETFHolding",
                "WarnPartialETFExpansion"
            ]
        }
    },
    "securityDefinitions": {
        "UserID": {
            "type": "apiKey",
            "name": "X-User-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Portfolio API",
	Description:      "A CRUD server for analyzing financial portfolios comprising stocks, bonds, and ETFs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
